version: '3'

services:
  postgresql:
    image: postgres:14.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
